export const songGenre = [

    // ===== CORE / TIMELESS =====
    "Classical",
    "Rock",
    "Pop",
    "Jazz",
    "Blues",
    "Hip Hop",
    "Rap",
    "R&B",
    "Soul",
    "Folk",
    "Country",

    // ===== RAP / HIP-HOP VARIANTS =====
    "Conscious Rap",
    "Boom Bap",
    "Trap Rap",
    "Drill Rap",
    "Cloud Rap",
    "Emotional Rap",
    "Poetry Rap",
    "Hardcore Rap",
    "Experimental Rap",

    // ===== ROYAL / HISTORICAL / ELITE =====
    "Baroque Court Music",
    "Medieval Chant",
    "Gregorian Chant",
    "Renaissance Music",
    "Royal Court Orchestral",
    "Imperial March Style",
    "Ancient Greek Lyric",
    "Persian Classical",
    "Ottoman Court Music",
    "Mughal Court Music",
    "Vedic Chant",
    "Samurai Era Music",
    "Feudal Japanese Court",
    "Victorian Era Music",
    "Colonial Era Orchestra",

    // ===== ROCK VARIANTS =====
    "Hard Rock",
    "Alternative Rock",
    "Progressive Rock",
    "Psychedelic Rock",
    "Punk Rock",
    "Post-Rock",
    "Indie Rock",
    "Garage Rock",
    "Arena Rock",
    "Art Rock",

    // ===== METAL / DARK =====
    "Metal",
    "Heavy Metal",
    "Doom Metal",
    "Black Metal",
    "Symphonic Metal",
    "Industrial Metal",
    "Gothic Metal",
    "Post-Metal",

    // ===== GOTHIC / DARK AESTHETIC =====
    "Gothic",
    "Gothic Rock",
    "Darkwave",
    "Ethereal Wave",
    "Dark Romantic",
    "Vampiric Gothic",
    "Cathedral Gothic",
    "Occult Gothic",

    // ===== ELECTRONIC / MODERN =====
    "EDM",
    "House",
    "Techno",
    "Trance",
    "Dubstep",
    "Drum and Bass",
    "Ambient",
    "IDM",
    "Synthwave",
    "Vaporwave",
    "Future Bass",
    "Electro Swing",
    "Hardstyle",

    // ===== URBAN / CONTEMPORARY =====
    "Lo-Fi",
    "Chillhop",
    "Afrobeats",
    "Reggaeton",
    "Dancehall",
    "Phonk",

    // ===== WORLD / TRADITIONAL =====
    "Reggae",
    "Flamenco",
    "Latin Pop",
    "Salsa",
    "Bachata",
    "Bossa Nova",
    "Celtic",
    "Middle Eastern",
    "Indian Classical",
    "Bollywood",
    "Qawwali",
    "Sufi Music",
    "Nordic Folk",
    "African Tribal",
    "Native American",

    // ===== CINEMATIC / EPIC =====
    "Cinematic Orchestral",
    "Film Score",
    "Epic Trailer Music",
    "Fantasy Soundtrack",
    "Dark Fantasy Score",
    "Mythological Epic",
    "War Anthem",
    "Heroic Orchestral",
    "Royal Coronation Theme",

    // ===== EXPERIMENTAL / ART =====
    "Experimental",
    "Avant-Garde",
    "Neo-Classical",
    "Post-Classical",
    "Minimalism",
    "Soundscape",
    "Drone Music",
    "Noise",
    "Industrial",
    "Dark Ambient",

    // ===== EMOTIONAL / AESTHETIC =====
    "Shoegaze",
    "Dream Pop",
    "Emo",
    "Sadcore",
    "Bedroom Pop",
    "Atmospheric Pop",
    "Melancholic Piano",

    // ===== SPOKEN / NARRATIVE =====
    "Spoken Word",
    "Narrative Ballad",
    "Storytelling Folk",
    "Opera Recitative"
];
